### ISSUE TITLE
state trail needs "no data" state

### ISSUE THREAD

**Issue by ijash** [hotNipi/node-red-contrib-ui-state-trail#1]
hi, for a suggestion/idea,

please add the state of _"unavailable"_. (or no data, or undefined, unreachable, etc..)

this is good if the state of a device is, _e.g_ not defined because of a disconnected network.

**Comment by hotNipi** [comment]
Well you can make string type state and call it as you like. And send it to the node when such condition are met. Usually disconnected devices don't send messages so it will be some logic in node-red flow which make that kind of decision.

Data with type undefined is not that easy to implement as it is indication of property value missing and it is used exactly for that reason.

**Comment by ijash** [comment]
> Well you can make string type state and call it as you like. And send it to the node when such condition are met. Usually disconnected devices don't send messages so it will be some logic in node-red flow which make that kind of decision.
> 
> Data with type undefined is not that easy to implement as it is indication of property value missing and it is used exactly for that reason.

that is correct it can be done like that.

additionally, **blank label** field can be useful too..
![image](https://user-images.githubusercontent.com/30673286/72224958-77e26d00-35b2-11ea-8c69-10ef572904ba.png)
thank you in advance..

**Comment by hotNipi** [comment]
Blank label until not enough data to display graph is reasonable. Will do.

**Comment by ijash** [comment]
Great! thanks for that!

**Comment by hotNipi** [comment]
Blank label option is available v0.1.3
