### ISSUE TITLE
Multiple graphs - based on msg.topic

### ISSUE THREAD

**Issue by Botched1** [hotNipi/node-red-contrib-ui-state-trail#10]
Would really like to see multiple "swim lane" graphs on one object., It would make it much easier to automate that graphing of multiple values dynamically.

msg.topic = "swim lane" id/key value
msg.payload = value to graph for the given msg.topic

**Comment by hotNipi** [comment]
Multi-line option has been asked before. There is a long list of things why it is not done so far. First of them will be too many restrictions to preserve at least some kind of performance and not to kill the browser. And those restrictions make current solution barely usable.
It must be something different, totally new widget.
