### ISSUE TITLE
Wont display chart on UI and makes everything else disappear 

### ISSUE THREAD

**Issue by MSS-Integrate** [hotNipi/node-red-contrib-ui-state-trail#12]
Hey Nipi,

I have some-what of a basic problem, as the node itself wont show in the UI and actually makes all other elements associated with the UI disappear and shows the standard message "Welcome to the Node-RED Dashboard, Please add some UI nodes to your flow and redeploy".

Mss

**Comment by hotNipi** [comment]
Please add info about environment and versions :

OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Node-RED version
Dashboard version
node-red-contrib-ui-state-trail version

**Comment by MSS-Integrate** [comment]
Hey, thanks for teh quick reply, heres the information 
OS: Windows 7, 64 bit
Browser: Google Chrome
Node-RED version: v. 1.0.6
Dashboard version: v. 2.22.1
node-red-contrib-ui-state-trail version: v. 0.3.0

**Comment by hotNipi** [comment]
Ok. Do you see any errors/warnings in node-red start up log?

**Comment by MSS-Integrate** [comment]
The Debug mode shows: 
"TypeError: Cannot read property 'push' of undefined" on the state trail node.

**Comment by hotNipi** [comment]
Do you run node red locally or docker or in cloud ?

**Comment by MSS-Integrate** [comment]
I run it locally.

**Comment by hotNipi** [comment]
Interesting.... What is the version of node-js

**Comment by MSS-Integrate** [comment]
Node-js is in v. 12.16.3

**Comment by hotNipi** [comment]
That sounds very strange. All versions seems to be good, but can't be sure about windows 7 and cant't test it currently. But should work..
Try following: remove all usages of the state-trail node, then uninstall it, then restart node-red, run some basic dashboard items to be sure you have cleaned it up properly, then install state-trail node again, and before any usage, restart node-red.

**Comment by MSS-Integrate** [comment]
Yea its quite strange.. 
I just removed all usage and uninstalled the state-trail node, afterwards i restarted Node-RED and depolyed a button which would be shown in the UI.
Afterwards i reinstalled the state-trail node, restarted Node-RED, and deployed the node, this resulted in the: "Welcome to the Node-RED Dashboard, Please add some UI nodes to your flow and redeploy" message, so again it made the whole UI disappear.

**Comment by hotNipi** [comment]
Can you explore the browser dev tools console for any related errors. 

Ignore. the dashboard does not run as you have runtime error serverside.

**Comment by MSS-Integrate** [comment]
The browser console displays 3 errors:

1. `Failed to load resource: the server responded with a status of 404 (Not Found)`

2. `WebSocket connection to 'ws://10.10.102.200:1880/ui/socket.io/?EIO=3&transport=websocket&sid=EvnARH6zHru1t64JAAAF' failed: Error during WebSocket handshake: Unexpected response code: 400
r.doOpen @ index.js:83`

3. `DevTools failed to load SourceMap: Could not load content for http://10.10.102.200:1880/ui/js/angular-chart.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by hotNipi** [comment]
This is expected and OK.

**Comment by hotNipi** [comment]
Can you show the node-red startup log?
If you have sensitive info in it, just replace with xxx or something like that.

**Comment by MSS-Integrate** [comment]
Thanks in advance,
Below is the log. Note: I am running Node-RED on custom directory "nr1882" and port 1882, however, I am able to reproduce the issue at a fresh install.

29 May 14:11:13 - [info] 

Welcome to Node-RED
===================

29 May 14:11:13 - [info] Node-RED version: v1.0.6
29 May 14:11:13 - [info] Node.js  version: v12.16.3
29 May 14:11:13 - [info] Windows_NT 6.1.7601 x64 LE
29 May 14:11:13 - [info] Loading palette nodes
29 May 14:11:14 - [info] Dashboard version 2.22.1 started at /ui
29 May 14:11:14 - [info] Settings file  : C:\xxx\nr1882\settings.js
29 May 14:11:14 - [info] Context store  : 'default' [module=memory]
29 May 14:11:14 - [info] User directory : C:\xxx\nr1882
29 May 14:11:14 - [warn] Projects disabled : editorTheme.projects.enabled=false
29 May 14:11:14 - [info] Flows file     : C:\xxx\nr1882\flows_TestServer.json
29 May 14:11:14 - [info] Server now running at http://127.0.0.1:1882/
29 May 14:11:14 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

29 May 14:11:14 - [info] Starting flows
29 May 14:11:14 - [info] Dashboard version 2.22.1 started at /ui
TypeError: Cannot read property 'widget-borderColor' of undefined
    at new StateTrailNode (C:\xxx\nr1882\node_modules\node-red-contrib-ui-state-trail\ui-state-trail.js:710:33)
    at Object.createNode (c:\Users\xxx\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\util.js:483:31)
    at Flow.start (c:\Users\xxx\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\Flow.js:193:48)
    at start (c:\Users\xxx\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\index.js:345:33)
    at tryCatchReject (c:\Users\xxx\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (c:\Users\xxx\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\makePromise.js:804:4)
    at Fulfilled.when (c:\Users\xxx\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\makePromise.js:592:4)
    at Pending.run (c:\Users\xxx\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (c:\Users\xxx\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (c:\Users\xxx\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\Scheduler.js:27:9)
29 May 14:11:14 - [info] Started flows
29 May 14:11:14 - [info] [mqtt-broker:MQTT Mosquitto] Connected to broker: mqtt://xx.xx.xx.xx:1883

**Comment by hotNipi** [comment]
Custom directory is the problem for sure.
I think I can probably fix some part of it from my nodes perspective, but something needs to be also investigated at dashboard side.

There is slight workaround but can't confirm it is reliable enough.
If you start creating dashboard from scratch, take some regular dashboard node first and deploy your flow and see the dashboard. Then place custom nodes and they should work without errors.
And may be custom nodes don't like to be alone on dashboard. 

I will do some research near future to fix this issue properly.

**Comment by hotNipi** [comment]
I fixed my widgets to not fall into error with this situation. 
I think there is one weakness (can't say it's issue the node-red guys will fix). You can reach the situation if you miss one deploy. That is if you create dashboard by adding widget, then do deploy, you then must visit the dashboard sidebar, which must again activate the deploy button. If you visit the dashboard page without deploy, it is error situation cos ui_base is not created yet for that moment.

**Comment by turner72** [comment]
Hi, I installed the state-trail node und would like to configure a chart showing the status of my KNX heating aktors (true/false). Unfortunately, I always get "TypeError: Cannot read property 'push' of undefined" when I deploy. I get this error even when the state-trail node is not connected to any other node. What could be the problem? 

I run the latest version of node red on a Raspi2. There is already a dashboard with some charts in place.

**Comment by hotNipi** [comment]
Please add
OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Node-RED version
nodejs version
Dashboard version
node-red-contrib-ui-state-trail version

**Comment by turner72** [comment]
Raspberry Pi OS (Raspian) latest Version
Chrome Version 83.0.4103.61
Node Red v1.0.6
Node.js  Version: v12.17.0
Dashboard 2.22.1
state-trail 0.3.0

**Comment by hotNipi** [comment]
Versions seems to be up to date.
Is it locally running setup or something different? (cloud, docker ...)

**Comment by turner72** [comment]
No, all locally on a Raspberry. Same network, no special things etc.

**Comment by turner72** [comment]
Thing is, the chart also does not show in the dashboard.

**Comment by hotNipi** [comment]
Then I think the problem is somewhere else but in state_trail node.

**Comment by turner72** [comment]
Error occurs only when state-trail node is added to some flow.

**Comment by hotNipi** [comment]
Have you tried to uninstall the node and install it again

**Comment by turner72** [comment]
Yes, same result. The nodes shows a small red triangle. Mouse over says "Invalid properties: - group".

**Comment by hotNipi** [comment]
No activities. Can close?
