### ISSUE TITLE
Time Offset

### ISSUE THREAD

**Issue by Bono1969** [hotNipi/node-red-contrib-ui-state-trail#13]
hi,
i have an offset of 2 Hours and i do not know wher to fix.
![Time Offset](https://user-images.githubusercontent.com/37637519/88654663-f7a6d380-d0cd-11ea-86ee-9d148b88a756.png)

**Comment by hotNipi** [comment]
Internally widget creates human-readable time using regular javascript Date() methods. Without any adjustments. 

MDN states:
_Note: It's important to keep in mind that while the time value at the heart of a Date object is UTC, the basic methods to fetch the date and time or its components all work in the local (i.e. host system) time zone and offset._

If you are sending in the data with timestamps: 
`msg.payload = {state:true,timestamp:1579362774639}`
then it is up to your implementation.

**Comment by Bono1969** [comment]
@hotNipi msg:
28.7.2020, 14:01:04node: bf55aedb.faa26
ns=2;s=S-201.MachineStatus : msg : Object
object
topic: "ns=2;s=S-201.MachineStatus"
payload: "200"
_msgid: "2140156d.3f80da"
![OPC String](https://user-images.githubusercontent.com/37637519/88662953-0ba50200-d0db-11ea-8345-b9f875f65cfb.png)

**Comment by Bono1969** [comment]
![Time Offset 2](https://user-images.githubusercontent.com/37637519/88663055-3727ec80-d0db-11ea-8c28-5b41e331ef3a.png)

**Comment by hotNipi** [comment]
What is the source of this time? 
![image](https://user-images.githubusercontent.com/35291460/88663869-e61cf600-d0e4-11ea-85f8-d6a31c1ca4fd.png)

**Comment by Bono1969** [comment]
@hotNipi this is from the Hardware where Node-Red is running
![Wut Box](https://user-images.githubusercontent.com/37637519/88665494-fdf17b80-d0de-11ea-82e6-f0f6fa3031dc.png)

**Comment by Bono1969** [comment]
![Template Clock Toolbar](https://user-images.githubusercontent.com/37637519/88666657-ace28700-d0e0-11ea-8bb9-f8bbb8dc4c44.png)

**Comment by hotNipi** [comment]
Node-RED server-side seems to run in different timezone. Widget creates tick-marks at server side. 
I think it is possible to move time parsing functionality to the front-end.

**Comment by hotNipi** [comment]
But to be sure, can you see node-red log with times and compare the times with dashboard times? Do they differ same way?

**Comment by Bono1969** [comment]
Your right. Node-Red is in UTC
I have to contact the Vendor of this Device, because there i didnt find anything to change that.
Thanks allot.

**Comment by hotNipi** [comment]
No  issue
