### ISSUE TITLE
Combine similar states

### ISSUE THREAD

**Issue by Bono1969** [hotNipi/node-red-contrib-ui-state-trail#14]
as i unchecked the "Combine" Funktion the Grafic starts to show segments (looks like Datapackages)
![Trail Node Settings](https://user-images.githubusercontent.com/37637519/88655623-4b65ec80-d0cf-11ea-8b02-4903a4947b4c.png)
![Trail Data Segments](https://user-images.githubusercontent.com/37637519/88655634-502aa080-d0cf-11ea-9b83-6ca0890e931b.png)

**Comment by Bono1969** [comment]
that is the msg String which feeds the Trail:

28.7.2020, 12:46:29node: ff598a38.5b7438
ns=2;s=S-201.MachineStatus : msg : Object
{ topic: "ns=2;s=S-201.MachineStatus", payload: "200", _msgid: "16d38564.f707cb" }

**Comment by hotNipi** [comment]
This is by design. 
Read more:
https://github.com/hotNipi/node-red-contrib-ui-state-trail#combine-similar-states

**Comment by hotNipi** [comment]
No issue
