### ISSUE TITLE
Use persistable storage if available

### ISSUE THREAD

**Issue by Bono1969** [hotNipi/node-red-contrib-ui-state-trail#15]
when i try to use the persistable storage, the Node tells me store: N/A
in which Folder is this routed?
![StatusTrail Storage](https://user-images.githubusercontent.com/37637519/88927735-2791da80-d278-11ea-9bcb-8bb3cab2b0ca.png)

**Comment by hotNipi** [comment]
N/A tells that persistable storage is not available. 
You will need to enable it from settings.js
Read more: https://github.com/hotNipi/node-red-contrib-ui-state-trail#data-storage

**Comment by Bono1969** [comment]
Thanks, i forward this to the Vendor of the Node-Red Hardware.
It seems, they have not implemented this in the "Standard" Way.

Thanks allot.

**Comment by hotNipi** [comment]
No issue
