### ISSUE TITLE
regular timebase update

### ISSUE THREAD

**Issue by kaepten-balu** [hotNipi/node-red-contrib-ui-state-trail#18]
Hi there and first of all thanks for the great tool!

I have a little proposal. I use node red to monitor some machines. The statetrail is displayed together with a graph that shows the produced quantity. The timeline of the graph refreshes regularly even if there is no new data. The statetrail does only if there is a new input. This leads to a huge asynchronity if comparing the data vertically, due to the completly different timebase.
Would it be possible to rescale the statetrail after a time even without new input? I know I could resend the last message after a time, but that would increase the data significantly. If the last interval would have a "sliding endpoint" it would be much better.  

<img width="1212" alt="Graph_and_statetrail" src="https://user-images.githubusercontent.com/80399388/110631550-eca93b00-81a6-11eb-9e1c-3a8668728006.png">

BR

**Comment by hotNipi** [comment]
_I know I could resend the last message after a time, but that would increase the data significantly._ 
That is exactly what you should do. 
If you have option "Combine similar states" selected, then behind the scenes if incoming state is same as previous, those last states are combined and the data-point between of them will be deleted. So only necessary data is kept.

You have to respect the timeline difference then only for period when state trail has not yet full range of data. It is just not possible to follow same timeline rendering rules as the charting library has :D

**Comment by kaepten-balu** [comment]
Hi hotNipi,

thanks for the fast answer! Looks like I missunderstood the "combine similar states" function. I was expecting that it would combine any data of the same state resulting in a time independent distribution. But, thinking about one more time, that wouldn't have made sense at all...

The remaining difference is no problem at all. As both have a time horizon of 8 hours and start at the same time there will be almost no more difference. Only these huge steps of half an hour or more were a little bit confusing.

Thanks again and BR!
