### ISSUE TITLE
timeline and shown states not equal

### ISSUE THREAD

**Issue by sniicker** [hotNipi/node-red-contrib-ui-state-trail#19]
![grafik](https://user-images.githubusercontent.com/67097444/112433752-fb652580-8d42-11eb-8dd7-242f34dda1f9.png)

I don't know if its a fault from my side or from the node but i identified a difference between the timeline and the shown states.
In the pic you can see the timeline. I want to show max 30h. 
I have data starting at around 21:00.
The green selected Status starts at 7:12.30 and is active till 7:33.12 but the timeline range is wrong.
It shows the status between 4 - 6 . 

What can i do do make the widget look right.

Nice greetings

**Comment by hotNipi** [comment]
For investigations it takes to have data and same setup for states.
You can store the state-trail input in parallel to sending it to widget. It should be stored as an array of objects, one object per state change, in form of event with the timestamp.
`{event:name, timestamp:1616667075}`
 If you notice the misbehavior, make screenshot, take stored data and add them to the issue report. Then it is possible to recreate the situation for analyse.

Thank you.

**Comment by hotNipi** [comment]
Published v 0.3.2 to solve issue https://github.com/hotNipi/node-red-contrib-ui-state-trail/issues/20
I'd guess it is related to same issue you have experienced.

**Comment by sniicker** [comment]
Can you also update npm?

**Comment by hotNipi** [comment]
Did just now. Forgot that step is required for flow listing.
