### ISSUE TITLE
pass timestamp

### ISSUE THREAD

**Issue by MaxRei-dev** [hotNipi/node-red-contrib-ui-state-trail#2]
Hi,
it would be nice to have the option to pass a timestamp in addition to the payload.
So it can be used when getting the data for example from an database.

kind regards 
Max

**Comment by hotNipi** [comment]
Possible. It will slightly ruin the optimizations I created but maybe it can be done as option to allow. Then the current solution can stay as it is.

**Comment by hotNipi** [comment]
Published v0.1.4
usage (live data) -> msg.payload = true
usage (historical data) -> msg.payload = {state:true,timestamp:1579362774639}
clear data -> msg.payload = []

Please let me know if something went really wrong. :)
