### ISSUE TITLE
Widget not working as it should

### ISSUE THREAD

**Issue by crushedy** [hotNipi/node-red-contrib-ui-state-trail#20]
I tried injecting into the widget the recommended values:
msg.payload = [
    {state:true,timestamp:1579362774639},
    {state:false,timestamp:1579362795665},
    {state:true,timestamp:1579362895432}
]
The settings of the UI were without persistent storage nor "Combine similar states". 
States were two of them, bool type.
The widget looked like this:
![image](https://user-images.githubusercontent.com/25159910/129575166-0f98f6ee-863f-4940-b0d1-b1e3b9c70557.png)
The timeline was ok, the change true - false - true was not. (FYI, the time of the first event was 15:52, the second 15:53 the last one 15:54).

Node-RED version: v1.3.5
Node.js  version: v10.19.0
Linux 5.8.0-1038-aws x64 LE

**Comment by hotNipi** [comment]
I cant see any issue here. 
The last change is from false to true and graph shows clearly that. Right most state (latest aka current state) is true. And the state time is 15.54.  Tested it and more precise change time is 15.54.55. 
I think the misleading thing is how the widget works.  The widget shows state changes over time. There is nothing after last timestamp. Widget does not place any timemarks by itself. All timestamps must be provided with input message. So no matter how long time has been passed from last input, the most right state treated as last input and timeline will no move until next input comes in. 
For historical data it is same. There is nothing after latest change, so there is no way to calculate how long the current state is or should be drawn. Therefore the current state (or last state change) fades out to right as not (jet) known abstraction of state.

**Comment by crushedy** [comment]
Thank you for the explanation of how the widget works. I was thinking the same. 
The issue which I wanted to point out is that the first change occurs at 15:52, the second one at 15:53 and the last one at 15:54. The one at 15:53 is not visible.
To better demonstrate I made another set of input vector, each event at one hour appart:
msg.payload = [
    {state:true,timestamp:1629136800000},   //18:00
    {state:false,timestamp:1629133200000},  //17:00
    {state:true,timestamp:1629129600000}    //16:00
]
The generated graph looks as in the picture below:
![image](https://user-images.githubusercontent.com/25159910/129626418-f2d85509-c3c8-400f-a289-4830fc7672c8.png)
I was expecting a change at 17:00 which does not happen.

**Comment by hotNipi** [comment]
Published version 0.3.2.
Time markers were one step off.

 Would you please give me some feedback if you can test it

**Comment by crushedy** [comment]
Works very nice now. Thank you!
