### ISSUE TITLE
Set Label via msg.control.label

### ISSUE THREAD

**Issue by deonp** [hotNipi/node-red-contrib-ui-state-trail#21]
Hi hotNipi,

I'd like to be able to set the label via the msg.control.label option so I can use it in a subflow.
Is this easily achievable?

**Comment by hotNipi** [comment]
Here you are :)
Version 0.4.3 available.
I'm just not sure you can use dashboard nodes with subflow. As far I know, it is not supported.

**Comment by deonp** [comment]
Thanks heaps for the very quick update, it works as expected.

Dashboard nodes work in subflows, but there are a few tricks and limitations including no control of the order.
