### ISSUE TITLE
Time always show as 01:16

### ISSUE THREAD

**Issue by msupra** [hotNipi/node-red-contrib-ui-state-trail#22]
Hi
I installed your component today, but the time shown in the legend always show 01:16, even thow the timestamp is the correct timestamp as can be seen below:
{"state":false,"timestamp":1638969632}
{"state":false,"timestamp":1638969634}
![Screenshot from 2021-12-08 15-27-52](https://user-images.githubusercontent.com/988506/145216338-a8902090-ebd5-432f-b6d6-e7ab70117ebe.png)

Regards
Morne

**Comment by hotNipi** [comment]
Correct timestamp has 13 digits. (1639031050140)
Your timestamps (1638969632) are a bit short.

**Comment by msupra** [comment]
Fantastic, thank you very much. I calculated in seconds instead of milli seconds.
