### ISSUE TITLE
How to show exactly 1 hour

### ISSUE THREAD

**Issue by sniicker** [hotNipi/node-red-contrib-ui-state-trail#24]
Hi,

iam using your node for some time now, but now i want to show some historical data.

For example i want to show 1h from the last day, between 10 & 11.

My input looks like this:

msg = {
    "payload": [
        {
            "state": 99,
            "timestamp": 1643792400000      // 10:00
        },
        {
            "state": 20,
            "timestamp": 1643794200000      // 10:30
        },
        {
            "state": 10,
            "timestamp": 1643795100000,     // 10:45
            "end": 1643796000000            // 11:00
        }
    ],
    "control" : {"period" : 3600000}        // 60 min
}

and your node show me this
![image](https://user-images.githubusercontent.com/67097444/152157564-8bf56561-a00a-437b-9f12-2712ebc37bee.png)

BUT thats not what i want do see.
I want to see this
![image](https://user-images.githubusercontent.com/67097444/152157692-c52182c9-f876-4229-ab2b-452c86ec6937.png)

I set the period to 1h and sent data for exactly  hour but your node only shows me 45min? 
I really tried hard, but i dont get it work. Can you pls help me.

Heres my flow:
`[{"id":"45de0810cffca933","type":"ui_statetrail","z":"7a256dd7ac6e4c50","group":"1f7aae446f091933","order":6,"width":"25","height":2,"name":"Timeline","label":"","states":[{"state":99,"col":"#e554c8","t":"num","label":"State1"},{"state":20,"col":"#2ecc71","t":"num","label":"State2"},{"state":10,"col":"#3498db","t":"num","label":"State3"}],"periodLimit":"1","periodLimitUnit":"1","timeformat":"HH:mm","tickmarks":"5","persist":false,"legend":"2","combine":false,"blanklabel":"... No Data ...","x":800,"y":420,"wires":[["fc7c81bfb27465fa"]]},{"id":"36a52fece4cb234c","type":"inject","z":"7a256dd7ac6e4c50","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":400,"y":420,"wires":[["9b861d974d878820"]]},{"id":"9b861d974d878820","type":"function","z":"7a256dd7ac6e4c50","name":"Set Time & Period","func":"msg = {\n    \"payload\": [\n        {\n            \"state\": 99,\n            \"timestamp\": 1643792400000      // 10:00\n        },\n        {\n            \"state\": 20,\n            \"timestamp\": 1643794200000      // 10:30\n        },\n        {\n            \"state\": 10,\n            \"timestamp\": 1643795100000,     // 10:45\n            \"end\": 1643796000000            // 11:00\n        }\n    ],\n    \"control\" : {\"period\" : 3600000}        // 60 min\n}\n\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":590,"y":420,"wires":[["45de0810cffca933"]]},{"id":"fc7c81bfb27465fa","type":"debug","z":"7a256dd7ac6e4c50","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":970,"y":420,"wires":[]},{"id":"168cf0e9877340b2","type":"inject","z":"7a256dd7ac6e4c50","name":"Clean","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[]","payloadType":"json","x":630,"y":460,"wires":[["45de0810cffca933"]]},{"id":"1f7aae446f091933","type":"ui_group","name":"TEST","tab":"d9298e3ba0dd7011","order":1,"disp":true,"width":"25","collapse":false,"className":""},{"id":"d9298e3ba0dd7011","type":"ui_tab","name":"TEST","icon":"dashboard","disabled":false,"hidden":false}]`

**Comment by hotNipi** [comment]
I'm a bit in hurry right now so can't explain in detail, but here's how it can be done:
```msg = {
 "payload": [
{
"state": 99,
"timestamp": 1643792000000 // added one before 10:00
},        
 {
 "state": 99,
 "timestamp": 1643792400000 // 10:00
 },
 {
 "state": 20,
 "timestamp": 1643794200000 // 10:30
 },
 {
 "state": 10,
 "timestamp": 1643795100000, // 10:45
 "end": 1643796000000 //you may omit the end but does not do any bad 11:00
 },
{
       "state": 99,
       "timestamp": 1643796000000 // added one starting at the end time 11:00
}

],
 "control" : {"period" : 4200000} // a bit more than 60 min. otherwise first one will be removed
}

return msg;```

**Comment by sniicker** [comment]
OK so i have to manipulate my data a little bit, but i got it. 

Thx for your fast response.
