### ISSUE TITLE
reference in historical data?

### ISSUE THREAD

**Issue by stefan242** [hotNipi/node-red-contrib-ui-state-trail#28]
In your description you wrote:

> The reference of state is additional data you can send to the widget. [...] Then by clicking on the error state, the payload from the widget contains also the reference object.
> [...]
> References can also be part of a historical data set. 

How do I add a reference to a historical data entry?

**Comment by hotNipi** [comment]
```
var msg2 = {
     payload: [ 
          { state: true, timestamp: startday , },
          { state: false, timestamp: startday + 1 * 60 * 60 * 1000 },
          { state: false, timestamp: startday + 6 * 60 * 60 * 1000 },
          { state: false, timestamp: startday + 9 * 60 * 60 * 1000},
          { state: false, timestamp: stopday, }
     ],
     reference: [         
          { item: 'one', timestamp: startday + 1 * 60 * 60 * 1000 },
          { explanatory: 'something very important',name:'nine',timestamp: startday + 9 * 60 * 60 * 1000 }
     ]
};
```

Reference is bounded to the state by matching timestamps. 
None of them will be sent over the socket to the dashboard. 
The click output manages to find correct reference for clicked item  at server side and includes reference to the msg with all properties as it was introduced.


![image](https://github.com/hotNipi/node-red-contrib-ui-state-trail/assets/35291460/9f14ca45-fed5-4fd5-96de-741e4bc1a1b3)

**Comment by stefan242** [comment]
Great! That works!!
