### ISSUE TITLE
Chart not displaying all states

### ISSUE THREAD

**Issue by psyllost** [hotNipi/node-red-contrib-ui-state-trail#4]
Hi,

I have noticed that in many occasions, not all available records are being shown in the chart. For example, when I configure the period to last 2 hours some states are missing, but when I choose last 2 minutes, the missing states are displayed. I expect that this is because of an overlap between states in the time aggregation (though their raw timestamps don't overlap).

I am wondering now if there is any good workaround for that?

**Comment by hotNipi** [comment]
This is strange. But as v0.2.6 is now available, could you please repeat the case with new version. Many changes done on that area and in addition, both your requests included. Any feedback is highly appreciated.  
PS, I'm afraid I did a soft breaking change so I'd like to hear about if first launch after update goes smoothly or there will be issues.

**Comment by hotNipi** [comment]
I was thinking about the issue more deeply. 2h is quite long period. The time scales down and if some state has really short duration it might be fall under 0.5 pixels width which is smallest thing the svg can render. I'm afraid, this can't be avoided. It will be reasonable to make whole chart wider if such conditions affect the readout of chart.

Experiments done on that topic
With following settings for widget
1x1 widget size 48x48
widget size 6x2 units
data period 1 minute
150 milliseconds is rendered
100 milliseconds is not rendered.

**Comment by psyllost** [comment]
Yes, that is the case.
I am sharing an example of data and how the chart looks like for 15min and 2h period. Quite a few records are missing because of the scaling.
[data.txt](https://github.com/hotNipi/node-red-contrib-ui-state-trail/files/4204115/data.txt)
![Capture1](https://user-images.githubusercontent.com/8641286/74524987-61686200-4f20-11ea-9f33-1161862b0587.PNG)
![Capture3](https://user-images.githubusercontent.com/8641286/74524989-62998f00-4f20-11ea-86dc-6bf5ccd1d4b0.PNG)

I think I will go with having arrows for going back and forth in time.

**Comment by hotNipi** [comment]
To make it possible to scale up around interesting places, it may require to send or just add to raw data periodically the "no event" record. Then there will be more data points to choose to start from. Otherwise the scaling does not let you to see tiny events from close look. Currently the long long empty periods on both ends of event affect the scaling so you cant even reach them, no mater the widget config.
I added a slight explanation about this to the widget docs also. https://github.com/hotNipi/node-red-contrib-ui-state-trail#the-scaling-time

**Comment by hotNipi** [comment]
Sure I can't do anything about the rendering limit. But seems to me the main problem is that if non-visible states exist, you can't find them visually. But I just got an idea how to make such tiny periods possible to discover. 
The solution is to introduce dots. Tiny colored dots above the chart bar. Dots don't scale, they will just placed and they "walk" according the time.
I'm not sure about the reliability of calculations whenever the dot is needed to be placed but I'll do my best :)

**Comment by psyllost** [comment]
This sounds good! I was also thinking to increase duration of those states to make them visible but I don't want to mess up with the statistics :/

**Comment by hotNipi** [comment]
Version 0.2.8 - the dots. Not sure if it is enough, but a step forward anyway.

**Comment by psyllost** [comment]
I think that should do the job! It looks good! Thank you very much for the quick fix :)
