### ISSUE TITLE
Support for Internet Explorer

### ISSUE THREAD

**Issue by psyllost** [hotNipi/node-red-contrib-ui-state-trail#8]
Hello,

I noticed that the legend is not displayed on my Internet Explorer version:
![image](https://user-images.githubusercontent.com/8641286/80123724-92ec5200-858f-11ea-8928-d3316e7dac9a.png)

It works fine on Firefox and Chrome.

Is there a plan for supporting IE?

Thank you for your time.

**Comment by hotNipi** [comment]
Hi, I don't even remember I ever tried with IE. Cos I dont have IE installed at home on any computer (and currently the home office is the only one) I cant test it. I can look at it tomorrow and make some educated guess why it is not working (many of SVG text placement rules don't work usually with old-school  browsers) but to make it work, it takes then the covid to go away.

**Comment by psyllost** [comment]
I am also not using IE :) Unfortunately, it's the default browser at work, thereby many colleagues still use it.
I don't get any error in the IE console.

Thank you for your time.

**Comment by hotNipi** [comment]
No errors is expected. The support of SVG for IE is partial an things fail silently.

**Comment by hotNipi** [comment]
Support isn't in  plans
